### ISSUE TITLE
Translate node domain in uci-defaults

### ISSUE THREAD

**Issue by gmarcos87** [LibreRouterOrg/openwrt#11]
**Describe the bug**
The file is currently located in the wrong folder. It should not go in /etc/config/uci-defaults but in /etc/uci-defaults

**To Reproduce**
1. build and flash a device
2. look in /etc/config/uci-defaults and the file is already there
3. look /etc/config/dhcp and see that there isn´t any change

**Expected behavior**
Add other domains in dhcp config

**Comment by gmarcos87** [comment]
And if you manualy run the script, you get:

> sed: bad option in substitution expression

**Comment by spiccinini** [comment]
Thanks marcos! Sorry for not testing it...I copy pasted another script that maybe wasn't also working :(

**Comment by spiccinini** [comment]
Fixed in 0e5d95057eb66113290c1d653087e7567a3f48a7 and 338454e2c9652b88a325c7545b1b98b979199fd6 (now tested!)
